# Generated by Django 5.2.17 on 2026-09-23 01:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='имя')),
            ],
            options={
                'verbose_name': 'автор',
                'verbose_name_plural': 'авторы',
                'constraints': [models.CheckConstraint(condition=models.Q(('name__regex', '^\\s*$'), _negated=True), name='author_name_not_blank')],
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='заголовок')),
                ('description', models.CharField(max_length=5000, verbose_name='описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('999999999.99'))], verbose_name='цена, ₽')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('archived', 'В архиве')], default='draft', max_length=16, verbose_name='статус')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='окончание публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ads', to='ads.author', verbose_name='автор')),
            ],
            options={
                'verbose_name': 'объявление',
                'verbose_name_plural': 'объявления',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', '-created_at', '-id'], name='ad_status_created_idx'), models.Index(fields=['status', 'expires_at'], name='ad_status_expires_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gte', Decimal('0')), ('price__lte', Decimal('999999999.99'))), name='ad_price_range'), models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'published', 'archived'])), name='ad_status_valid'), models.CheckConstraint(condition=models.Q(('title__regex', '^\\s*$'), _negated=True), name='ad_title_not_blank'), models.CheckConstraint(condition=models.Q(('description__regex', '^\\s*$'), _negated=True), name='ad_description_not_blank')],
            },
        ),
    ]
